[package]
name = "main"
version = "0.1.0"
authors = ["Igor Line <linesethenoiz@gmail.com>", "Klim Kolyvanov <klim.kolyvanov@gmail.com>"]
edition = "2018"

[dependencies]
serde = "=1.0.89"
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
serde_derive = "=1.0.89"
hdk = { git = "https://github.com/holochain/holochain-rust", tag = "0.0.24-alpha2" }
hdk-proc-macros = { git = "https://github.com/holochain/holochain-rust", tag = "0.0.24-alpha2" }
holochain_wasm_utils = { git = "https://github.com/holochain/holochain-rust", tag = "0.0.24-alpha2" }
holochain_json_derive = "=0.0.15"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
